---
# Calamares users module — AetherOS
# Disable strict password requirements (no dictionary check)

userGroup:       users
defaultGroups:
    - name: sudo
      must_exist: false
      system: false
    - name: audio
      must_exist: false
      system: false
    - name: video
      must_exist: false
      system: false
    - name: plugdev
      must_exist: false
      system: false
    - name: netdev
      must_exist: false
      system: false
    - name: bluetooth
      must_exist: false
      system: false
    - name: dialout
      must_exist: false
      system: false

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    sudo
setRootPassword: false

# No password strength requirements
passwordRequirements:
    minLength: 1
    maxLength: -1
    libpwquality:
        - minlen=1
        - minclass=0
        - badwords=
        - dictcheck=0
        - usercheck=0
        - enforcing=0
